/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Out.java
 *
 * Created on Apr 17, 2014, 12:32:40 PM
 */
package ValetPark;

import java.awt.Component;
import javax.swing.JButton;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Vaibhav
 */
public class Out extends javax.swing.JFrame {
    PreparedStatement pst,ps;
    ResultSet rs;
    public String start_time = null, Name=null, Vehicle=null, status=null, exit=null;
public int check, updated_row_count=0, n;
    private Component frame;
    /** Creates new form Out */
    public Out(int set) {
        initComponents();
               check = set;
        setLabel(set);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ValetPark.DesktopApplication1.class).getContext().getResourceMap(Out.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jTextField1.setFont(resourceMap.getFont("jTextField1.font")); // NOI18N
        jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.setName("jTextField1"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jButton1.setFont(resourceMap.getFont("jButton1.font")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(resourceMap.getFont("jButton2.font")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

public static Out cancel = null;
public static JButton jb1,jb2;
public static boolean choice = true;
public static void tempout(Out tempout,JButton jb, JButton jbt)
{
cancel = tempout;
jb1 = jb;
jb2 = jbt;

}

private void setLabel(int i)
{
if(i==1)
{
    jLabel1.setText("TOKEN NO #. :");    
}
else
{
    jLabel1.setText("Registration No:");
}
}

private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked


cancel.dispose();
jb1.setEnabled(true);
jb2.setEnabled(true);
cancel = null; 

}//GEN-LAST:event_jButton2MouseClicked

private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
String timeStamp = new SimpleDateFormat("dd/MM/YYYY_HH:mm").format(Calendar.getInstance().getTime());
    int tally = 0;
    // DATABASE CONNECTIVITY FOR VECHICLE EXIT
    if(check==1)
    {
      try {
int Token = Integer.parseInt(jTextField1.getText());
System.out.println("This is an integer " + Token);              
}
catch (NumberFormatException x) {
JOptionPane.showMessageDialog(frame, x.getMessage()+"\nNot A Valid Token No.");
    System.out.println("Error : "+ x.getMessage());
    jTextField1.setText("");
tally=1;
}  
    
      if(tally!=1)
      {
      try
   {
    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
    Connection con = DriverManager.getConnection("jdbc:odbc:valet");
    
    String Token = jTextField1.getText();
    
   String query1="UPDATE valet.dbo.ValetInfo SET Status='OUT', Exit_Time='"+timeStamp+"' WHERE Token = '"+Token+"'";
   String query2="Select Customer_Name,Vehicle_No,Entry_Time,Exit_Time,Status from valet.dbo.ValetInfo Where Token = '"+Token+"'"; 
   
   ps = con.prepareStatement (query2);
  rs=ps.executeQuery();
  
  while(rs.next())
  {
  Name = rs.getString("Customer_Name");
  Vehicle = rs.getString("Vehicle_No");    
  start_time=rs.getString("Entry_Time");
  exit = rs.getString("Exit_Time");
  status = rs.getString("Status");
  
  }
 System.out.println("Status = "+status);  
  if(Vehicle==null)
  {
  updated_row_count = 0;
  }
  else if(status.equals("OUT")){JOptionPane.showMessageDialog(frame, "THIS VEHICLE IS Already Exited at "+exit+"!"); }
  else
  {
  Object[] options = {" Confirm ",
                    "No way!"};
 n = JOptionPane.showOptionDialog(frame,
    "Are You Sure ?\nDo You Really Want to CheckOut Vehicle ?\n------------------------------------------\nDetails of Vehicle:\nName : "+Name+"\nVehicle No. : "+Vehicle+" ",
    "Confirmation....",
    JOptionPane.YES_NO_OPTION,
    JOptionPane.QUESTION_MESSAGE,
    null,     
    options,  
    options[0]);  
  
  }
 if(n==0&&status.equals("IN"))
 {
   pst = con.prepareStatement(query1);
  pst.execute();
  updated_row_count = pst.getUpdateCount(); 
 }
 else{
 updated_row_count = 4;
 }
    System.out.println(updated_row_count);
                
                if(updated_row_count==0)
                {
                
                   JOptionPane.showMessageDialog(frame,"TOKEN NUMBER NOT FOUND\nNO Such Token Number Assigned"); 
                    jTextField1.setText(null);
                }
                
                else if (updated_row_count == 1)
                {
                   Amount a = new Amount();
                   long amount = a.calc_amount(start_time,timeStamp,Name,Vehicle);
                   int Amount = (int) amount;
                   String query3="UPDATE valet.dbo.ValetInfo SET Amount = "+Amount+" Where Vehicle_No = '"+Vehicle+"'";
                   pst = con.prepareStatement(query3);
                   pst.execute();
                   con.close();
                    System.out.println("OK4");
                    cancel.dispose();
                    cancel=null;
                    jb1.setEnabled(true);
                    jb2.setEnabled(true);
                }
                else{
                    jTextField1.setText(null);
                Vehicle=null;
                }
    
   }
   catch(Exception ex)
   {
       System.out.println(ex);
      JOptionPane.showMessageDialog(frame, ex.getMessage()); 
      
   
   }
      }
      // Inner Else
      else{
      
      tally = 0;
    JOptionPane.showMessageDialog(frame, "Not A Valid Token No.");
      
      } 
    }
    
    
    // Outer Else
    else
    {
    // Vehicle Out BY REGISTRATION NO.
        
        System.out.println("By Registration No.");
         
String Vehicle_No = jTextField1.getText().toUpperCase();
          

if(Vehicle_No.length()<9)
{
    JOptionPane.showMessageDialog(frame, "Not A Valid Registratioin No.");
    jTextField1.setText("");
    tally = 1;
}
 
    
      if(tally!=1)
      {
      try
   {
    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
    Connection con = DriverManager.getConnection("jdbc:odbc:valet");
    System.out.println("OK0");
   
   String query1="UPDATE valet.dbo.ValetInfo SET Status='OUT', Exit_Time='"+timeStamp+"' WHERE Vehicle_No = '"+Vehicle_No+"'";
   String query2="Select Customer_Name,Vehicle_No,Entry_Time, Exit_Time,Status from valet.dbo.ValetInfo Where Vehicle_No = '"+Vehicle_No+"'"; 
 
   ps = con.prepareStatement (query2);
  rs=ps.executeQuery();
  
  while(rs.next())
  {
  Name = rs.getString("Customer_Name");
  Vehicle = rs.getString("Vehicle_No");    
  start_time=rs.getString("Entry_Time");
  exit = rs.getString("Exit_Time");
  status = rs.getString("Status");
  
  }
 if(Vehicle==null)
  {
  updated_row_count = 0;
  }
 else if(status.equals("OUT")){JOptionPane.showMessageDialog(frame, "THIS VEHICLE IS Already Exited at "+exit+"!"); }
 else
 {
  Object[] options = {" Confirm ",
                    "No way!"};
 n = JOptionPane.showOptionDialog(frame,
    "Are You Sure ?\nDo You Really Want to CheckOut Vehicle ?\n------------------------------------------\nDetails of Vehicle:\nName : "+Name+"\nVehicle No. : "+Vehicle+" ",
    "Confirmation..!!",
    JOptionPane.YES_NO_OPTION,
    JOptionPane.QUESTION_MESSAGE,
    null,     
    options,  
    options[0]); 
 }  
  if(n==0&&status.equals("IN"))
  {  

  pst = con.prepareStatement(query1);
  pst.execute();
  updated_row_count = pst.getUpdateCount();
  }
  else{
  
  updated_row_count = 3;
  }
  
                if(updated_row_count==0)
                {
                
                   JOptionPane.showMessageDialog(frame,"REGISTRATION NUMBER NOT FOUND\nNO Such Registration Number Recorded"); 
                    jTextField1.setText(null);
                }
                
                
                
                else if (updated_row_count==1)
                {
                  Amount a = new Amount();
                   long amount = a.calc_amount(start_time,timeStamp,Name,Vehicle);
                    int Amount = (int) amount;
                   String query3="UPDATE valet.dbo.ValetInfo SET Amount = "+Amount+" Where Vehicle_No = '"+Vehicle+"'";
                   pst = con.prepareStatement(query3);
                   pst.execute();
                    con.close();
                    System.out.println("OK4");
                    cancel.dispose();
                    cancel=null;
                    jb1.setEnabled(true);
                    jb2.setEnabled(true);
                }
    
                else{
                    Vehicle=null;
                    jTextField1.setText(null);
                }
   }
   catch(Exception ex)
   {
       System.out.println(ex);
       JOptionPane.showMessageDialog(frame, ex.getMessage());
       jTextField1.setText("");
   
   }
      }
      // Inner Else
      else{
      
      tally = 0;
   
      jTextField1.setText(null);
      } 
        
    }
    
    
}//GEN-LAST:event_jButton1MouseClicked




    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Out(1).setVisible(true);
           
            }
            
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
